# .github/workflows/ci.yml

name: MLOps CI/CD Pipeline

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs for the pipeline
jobs:
  # Job 1: Train the model and run the test suite
  train_and_test:
    name: Train Model and Run Tests
    runs-on: ubuntu-latest
    steps:
      # Step to check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step to set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      # Install system dependencies for scipy and numpy
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev gfortran

      # Install project dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # pytest is not in requirements.txt

      # Run the training script to generate the model artifact
      - name: Run training script
        run: |
          python src/train.py

      # Run the quantization script to generate the quantized parameters
      - name: Run quantization script
        run: |
          python src/quantize.py
          
      # Run the unit tests with pytest after the model has been created
      - name: Run pytest
        run: |
          pytest
      
      # Upload the model and quantization artifacts for the next job
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: models/

  # Job 2: Build the Docker image and verify it works
  build_and_test_container:
    name: Build and Test Docker Container
    runs-on: ubuntu-latest
    needs: train_and_test # This job depends on the training/testing job passing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download the artifacts generated in the previous job
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: models/

      # Log in to Docker Hub using GitHub Secrets for security
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: nitinsoni2302
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t nitinsoni2302/mlops-linear-regression .

      # Run the container and execute predict.py for verification
      - name: Run and test container
        run: |
          docker run --rm nitinsoni2302/mlops-linear-regression python src/predict.py

      # Push the final Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push nitinsoni2302/mlops-linear-regression
